job_details:
  name: avg_sweep_10%_warmup
  output_dir: exps
  num_nodes: 2
  num_gpus: 4
parameters:
    LIST_ACC_BS:
      - model: ['layers=8_hidden-dim=288'] #
        accum_freq: [1] 
        train_num_samples: [4497408] # 4.49M so x100 = 449.7M
        warmup_tokens: [44974080]
      - model: ['layers=12_hidden-dim=480']
        accum_freq: [1]
        train_num_samples: [11476992] # 11.48M so x100 = 1.148B
        warmup_tokens: [114769920]
      - model: ['layers=15_hidden-dim=640'] # later - limit jobs (or remove)
        accum_freq: [1] 
        train_num_samples: [21200896] # 21.2M so x100 = 2.12B
        warmup_tokens: [212008960]
    batch_size: [8]
    lr: [0.0015] 
    lr_scheduler: ['const']
    # warmup: [200]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    lr_cooldown_end: [0.0]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    wd: [0.033]
    epochs: [100]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [120] # we have 6 averagers 
    delete_previous_checkpoint: [true]
    averagers: ['poly_2_1,poly_4_1']
    workers: [2]
    train_data: ["/p/fastdata/mmlaion/lmdata_2/refined_web_tokenized/{00001001..00042512}.tar"]
    # flops_to_save: ['2.00e+15,4.00e+15,8.00e+15,1.60e+16,3.20e+16,6.40e+16,1.28e+17,2.56e+17,5.12e+17,1.02e+18,2.05e+18,4.10e+18,8.19e+18,1.64e+19,3.28e+19,6.55e+19']
    # max_checkpoints_flops: [5] 
