job_details:
  name: bs_comparison_RW_decouled_wd_2
  output_dir: exps
  # num_nodes: 1
  # num_gpus: 4
parameters:
    LIST_ACC_BS:
      # - model: ['layers=3_hidden-dim=96']
      #   accum_freq: [1]
      #   train_num_samples: [5170000] # 5.17M, so x10 = 51.7M
      #   warmup_tokens: [5170000]
      - model: ['layers=3_hidden-dim=96']
        accum_freq: [1]
        train_num_samples: [517000000] # 51.7M, so x10 = 0.517B (this model with x100 tok. mult.)
        warmup_tokens: [517000000]
      # - model: ['layers=4_hidden-dim=128']
      #   accum_freq: [1]
      #   train_num_samples: [7240000] # 7.24M, so x10 = 72.4M
      #   warmup_tokens: [7240000]
      # - model: ['layers=5_hidden-dim=160']
      #   accum_freq: [1]
      #   train_num_samples: [9610000] # 9.61M, so x10 = 96.1M
      #   warmup_tokens: [9610000]
    LIST_BS_LR: # due to job limitiations, we run extra 4 lrs and not 5. if needed more will be added
      - batch_size: [16]
        lr: [0.003, 0.006, 0.012, 0.024]
      - batch_size: [8]
        lr: [0.00212, 0.00424, 0.00848, 0.01696]
      - batch_size: [4]
        lr: [0.0015, 0.003, 0.006, 0.012]
      - batch_size: [2]
        lr: [0.00106, 0.00212, 0.00424, 0.00848]
      - batch_size: [1] 
        lr: [0.00075, 0.0015, 0.003, 0.006]
    decoupled_wd: [1.0e-4]
    lr_scheduler: ['cosine']
    # warmup: [200]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json.gz']
    lr_cooldown_end: [0.0]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    # wd: [0.033]
    epochs: [10]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    delete_previous_checkpoint: [true]
    # keep_freq: [5]
    # keep_from: [75]
    workers: [2]
    train_data: ["/p/scratch/laionize/smyrnis1/refined_web_tokenized/{00001001..00042512}.tar"]
    # flops_to_save: ['2.00e+15,4.00e+15,8.00e+15,1.60e+16,3.20e+16,6.40e+16,1.28e+17,2.56e+17,5.12e+17,1.02e+18,2.05e+18,4.10e+18,8.19e+18,1.64e+19,3.28e+19,6.55e+19']
    # max_checkpoints_flops: [5] 
