job_details:
  name: c4_adam_betas_more_bs
  output_dir: results
  num_gpus: 1
  num_nodes: 1
parameters:
    save_checkpoint: [false]
    LIST_MODEL_WARMUP_TOKENS:

      - model: ['layers=6_hidden-dim=224']
        max_tokens: [2069299200] 
      
    warmup: [6115]
    train_num_samples: [10000000]
    val_num_samples: [2000]
    # ~130B as in kaplan (note that we set 1000 epochs for avoiding repeating too much data in resuming),
    # but we will never reach that - we will stop after 6 or 12 hours.
    dataset_resampled: [true]
    precision: ['float16']
    LIST_OF_BATCHES:
      # - batch_size: [1]
      #   accum_freq: [1]
      #   val_freq: [1]
      # - batch_size: [4] # global batch size is 16*4=64
      #   accum_freq: [1]
      #   val_freq: [1]
      # - batch_size: [16]
      #   accum_freq: [4]
      #   val_freq: [1]
      # - batch_size: [64]
      #   accum_freq: [16]
      #   val_freq: [4]
      - batch_size: [2]
        accum_freq: [1]
        val_freq: [1]
      - batch_size: [8]
        accum_freq: [2]
        val_freq: [1]
      - batch_size: [32]
        accum_freq: [8]
        val_freq: [2]
      - batch_size: [128]
        accum_freq: [32]
        val_freq: [8]
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [null]
    beta1: eval("[ 1 - 10**(-k/2) for k in range(0,7) ]")
    beta2: [0.999]
    eps: [1.0e-08]
    report_to: [""] # 'wandb'
    resume: ['latest']
    data_key: ['txt']
    lr_cooldown_end: [3.0e-05] # in the rpj config it was like that, so I keep it
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['cosine']
    decoupled_wd: [0.0001]
    lr: [1.0e-01, 1.0e-02, 1.0e-03]
    epochs: [50]
    wandb_project_name: ['c4_test']
    delete_previous_checkpoint: [true]
    workers: [4]
    train_data: ["/home/ycarmon/data/wds/c4/train/shard-{0000000..0000360}.tar"]
    val_data: ["/home/ycarmon/data/wds/c4/validation/shard-0000000.tar"]
    averagers: ['poly_32_1']
    optim_alg: ['adamw']
    # if there are 600B tokens in RW, and all of them are uniformly distributed in the shards, then each shard has 600B/42512 = 14.1M tokens
    # so, keeping 1000 shards for validation, we have 1000*14.1M = 14.1B tokens for validation