job_details:
  name: openwebtext_ladam_avg
  output_dir: results
  num_gpus: 1
  num_nodes: 1
parameters:
    save_checkpoint: [false]
    LIST_MODEL_WARMUP_TOKENS:

      - model: ['layers=6_hidden-dim=224']
        max_tokens: [2069299200]
      # - model: ['layers=10_hidden-dim=384']
      #   max_tokens: [2069299200] 
      
    warmup_tokens: eval("[ 10000000 * 5 ]")
    train_num_samples: [10000000]
    val_num_samples: [2000]
    # ~130B as in kaplan (note that we set 1000 epochs for avoiding repeating too much data in resuming),
    # but we will never reach that - we will stop after 6 or 12 hours.
    dataset_resampled: [false]
    precision: ['float16']
    LIST_OF_BATCHES:
      - batch_size: [1]
        accum_freq: [1]
        val_freq: [1]
      - batch_size: [4] # global batch size is 16*4=64
        accum_freq: [1]
        val_freq: [1]
      - batch_size: [16]
        accum_freq: [4]
        val_freq: [1]
      - batch_size: [64]
        accum_freq: [16]
        val_freq: [4]
      - batch_size: [2]
        accum_freq: [1]
        val_freq: [1]
      - batch_size: [8]
        accum_freq: [2]
        val_freq: [1]
      - batch_size: [32]
        accum_freq: [8]
        val_freq: [2]
      - batch_size: [128]
        accum_freq: [32]
        val_freq: [8]
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    beta1: [0.9] # eval("[ 1 - 10**(-k/2) for k in range(0,7) ]")
    beta2: [0.999]
    eps: [1.0e-08]
    report_to: ['wandb'] # 
    resume: ['latest']
    data_key: ['json.gz']
    lr_cooldown_end: [3.0e-05] # in the rpj config it was like that, so I keep it
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['cosine']
    decoupled_wd: [0.0001]
    lr: [3.16e-02, 3.16e-03, 3.16e-04, 1.0e-01, 1.0e-02, 1.0e-03]
    epochs: [50]
    wandb_project_name: ['openwebtext_ladam_avg']
    delete_previous_checkpoint: [true]
    workers: [4]
    dataset_manifest: ["data/openwebtext2_tokenized/manifest_train.jsonl"]
    val_data: ["data/openwebtext2_tokenized/00000026.tar"]
    averagers: ['poly_8_1']
    optim_alg: ['adamw']
    dog_granularity: ['param']
    granularity_per_token: [false,true]
    granularity_attentions: [false] # [false,true] #
    granularity_feed_forward: [false] # [false,true] #
    granularity_reverse: [false] # [false,true] #
    ladamw_g_op: ['avg']
    # if there are 600B tokens in RW, and all of them are uniformly distributed in the shards, then each shard has 600B/42512 = 14.1M tokens
    # so, keeping 1000 shards for validation, we have 1000*14.1M = 14.1B tokens for validation