job_details:
  name: openwebtext_dog_reps
  output_dir: results
  num_gpus: 1
  num_nodes: 1
parameters:
    save_checkpoint: [false]
    LIST_MODEL_WARMUP_TOKENS:

      - model: ['layers=6_hidden-dim=224']
        max_tokens: [2069299200]
      # - model: ['layers=10_hidden-dim=384']
      #   max_tokens: [2069299200] 
      
    train_num_samples: [10000000]
    val_num_samples: [2000]
    # ~130B as in kaplan (note that we set 1000 epochs for avoiding repeating too much data in resuming),
    # but we will never reach that - we will stop after 6 or 12 hours.
    dataset_resampled: [false]
    precision: ['float16']
    LIST_OF_BATCHES:
      - batch_size: [1]
        accum_freq: [1]
        val_freq: [1]
      - batch_size: [4] # global batch size is 16*4=64
        accum_freq: [1]
        val_freq: [1]
      - batch_size: [16]
        accum_freq: [4]
        val_freq: [1]
      # - batch_size: [64]
      #   accum_freq: [16]
      #   val_freq: [4]
      # - batch_size: [2]
      #   accum_freq: [1]
      #   val_freq: [1]
      # - batch_size: [8]
      #   accum_freq: [2]
      #   val_freq: [1]
      # - batch_size: [32]
      #   accum_freq: [8]
      #   val_freq: [2]
      # - batch_size: [128]
      #   accum_freq: [32]
      #   val_freq: [8]
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    eps: [1.0e-08]
    report_to: ['wandb'] # 
    resume: ['latest']
    data_key: ['json.gz']
    lr_cooldown_end: [3.0e-05] # in the rpj config it was like that, so I keep it
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    epochs: [50]
    wandb_project_name: ['openwebtext_dog_reps']
    delete_previous_checkpoint: [true]
    workers: [4]
    dataset_manifest: ["data/openwebtext2_tokenized/manifest_train.jsonl"]
    val_data: ["data/openwebtext2_tokenized/00000026.tar"]
    averagers: ['poly_8_1']
    LIST_OF_OPTIM:
      - optim_alg: ['dog','accele_dog']
        ladamw_g_op: ['avg']
        warmup_tokens: eval("[ 0 ]")
        lr_scheduler: ['const']
        decoupled_wd: [0.0]
        lr: [1.0]
        beta1: [1.]
        beta2: [1.]
        dog_init_dist_rel: [1.0e-06,1.0e-05, 1.0e-04,1.0e-03, 1.0e-02, 1.0e-01, 1.0e-0]
        normalize_rbar: [true,false]
        dog_decay_to_init: [false]
    max_rbar: [false]
    decouple_decay: [true]
    decay_factor: [1.0]
    dog_granularity: ['param']
    granularity_norm: [false]
    granularity_per_token: [true] # [false] # 
    granularity_per_param: [false] # [true] # 
    granularity_attentions: [true]
    granularity_feed_forward: [true]
    # if there are 600B tokens in RW, and all of them are uniformly distributed in the shards, then each shard has 600B/42512 = 14.1M tokens
    # so, keeping 1000 shards for validation, we have 1000*14.1M = 14.1B tokens for validation