job_details:
  name: space_time_measurement_avg
  output_dir: exps
parameters:
    model: ['layers=18_hidden-dim=704', 'layers=23_hidden-dim=1024','layers=26_hidden-dim=1312'] 
    train_num_samples: [4267660] # ~42M
    warmup: [20]
    dataset_resampled: [false]
    precision: ['amp_bfloat16']
    batch_size: [16]
    grad_checkpointing: [true]
    log_every_n_steps: [20]
    csv_log: [true]
    grad_clip_norm: [1]
    warmup: [2000]
    beta1: [0.9]
    beta2: [0.95]
    eps: [1.0e-08]
    report_to: ['wandb']
    resume: ['latest']
    data_key: ['json']
    lr_cooldown_end: [3.0e-05]
    qk_norm: [true]
    z_loss_coefficient: [0.0001]
    lr_scheduler: ['const']
    wd: [0.033]
    lr: [3.0e-03]
    epochs: [10]
    wandb_project_name: ['lm_grid_160m_more_avgs']
    log_avg_model_training_loss: [20]
    # delete_previous_checkpoint: [true]
    # keep_powers_of_two: [5]
    workers: [2]
    accum_freq: [1,2,4]
    averagers: ['poly_64']
    # fsdp: [true]
    # fsdp_amp: [true]
    # fsdp_limit_all_gather: [true]
    train_data: ["/p/scratch/ccstdl/smyrnis1/rw_v2_fasttext_openhermes_vs_rw_v2_bigram_0.1/{00000005..00001747}.tar"]